title: You have been warned!
author: Sadiha
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In all the parallels there is, you and i get along in a *pi*.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
